export const soldMotorsData = [
    {
      id: '1',
      title: 'Audi A5',
      variant: '2.0 TFSI 150 S Line 4dr S Tronic',
      numberPlate: 'DS74 KLM',
      condition: 'Used',
      timeListed: '15m ago',
      price: '£35,044',
      cap: 35044,
      capStrike: 38335,
      status: 'OFFER RECEIVED',
      dealer: {
        name: 'Premier Autos',
        address: '88 Queens Road, Birmingham, B15 2TX',
        contactName: 'Daniel Lee',
        phone: '0791 234 5678',
        email: 'a5@premierautos.co.uk',
      },
      vehicleInfo: {
        year: 2021,
        color: 'White',
        engine: '2.0 L',
        miles: '22,000',
        fuel: 'Petrol',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: false,
      },
    },
    {
      id: '2',
      title: 'Mercedes-Benz CLS',
      variant: 'CLS 350d AMG Line 4dr 9G-Tronic',
      numberPlate: 'LP19 RET',
      condition: 'Certified',
      timeListed: '40m ago',
      price: '£24,650',
      cap: 24550,
      capStrike: 27560,
      status: 'OFFER RECEIVED',
      dealer: {
        name: 'Elite Motors',
        address: '5 Crescent Road, Glasgow, G20 4AQ',
        contactName: 'Linda Zhao',
        phone: '0788 456 7890',
        email: 'cls@elitemotors.co.uk',
      },
      vehicleInfo: {
        year: 2019,
        color: 'Blue',
        engine: '3.0 L',
        miles: '45,000',
        fuel: 'Diesel',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: true,
      },
    },
    {
      id: '3',
      title: 'Tesla Model S',
      variant: 'Performance Ludicrous AWD 5dr Auto',
      numberPlate: 'LG19 UHD',
      condition: 'Like New',
      timeListed: '2hrs ago',
      price: '£33,985',
      cap: 33985,
      capStrike: 35090,
      status: 'FOR SALE',
      dealer: {
        name: 'FutureDrive EVs',
        address: '301 Green Park, Reading, RG2 6UJ',
        contactName: 'Ibrahim Khan',
        phone: '0770 112 3344',
        email: 'tesla@futuredrive.co.uk',
      },
      vehicleInfo: {
        year: 2019,
        color: 'Red',
        engine: 'Electric',
        miles: '18,000',
        fuel: 'Electric',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: true,
      },
    },
    {
      id: '4',
      title: 'Audi SQ2',
      variant: 'SQ2 Quattro 5dr S Tronic',
      numberPlate: 'DS74 KLM',
      condition: 'Used',
      timeListed: '3hrs ago',
      price: '£28,752',
      cap: 28752,
      capStrike: 29778,
      status: 'IDLE',
      dealer: {
        name: 'AutoZone UK',
        address: '22 Motorway Lane, Leeds, LS10 2TY',
        contactName: 'Nina Patel',
        phone: '0755 678 9001',
        email: 'sq2@autozoneuk.co.uk',
      },
      vehicleInfo: {
        year: 2022,
        color: 'Grey',
        engine: '2.0 L',
        miles: '12,000',
        fuel: 'Petrol',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: false,
      },
    },
    {
      id: '5',
      title: 'Audi A5',
      variant: '2.0 TFSI 150 S Line 4dr S Tronic',
      numberPlate: 'DS74 KLM',
      condition: 'Used',
      timeListed: '4hrs ago',
      price: '£35,044',
      cap: 35044,
      capStrike: 38335,
      status: 'ARCHIVED',
      dealer: {
        name: 'Premier Autos',
        address: '88 Queens Road, Birmingham, B15 2TX',
        contactName: 'Daniel Lee',
        phone: '0791 234 5678',
        email: 'a5@premierautos.co.uk',
      },
      vehicleInfo: {
        year: 2021,
        color: 'White',
        engine: '2.0 L',
        miles: '22,000',
        fuel: 'Petrol',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: false,
      },
    },
  ];