export const vehicleData = [
    {
      id: '1',
      title: 'BMW 4 Series Gran Coupe',
      variant: '420d [190] M Sport 5dr Auto',
      numberPlate: 'BE20 UHG',
      condition: 'Like New',
      timeListed: '35m ago',
      price: '£17,849',
      dealer: {
        name: 'ProHatch Cars',
        address: '106 Jam Road, Bristol, BS47 2HJ',
        contactName: 'Jason Murray',
        phone: '0789 123 4567',
        email: 'bmw@prohatchcars.co.uk',
      },
      vehicleInfo: {
        year: 2020,
        color: 'Midnight',
        engine: '2.0 L',
        miles: '32,000',
        fuel: 'Diesel',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: true,
      },
    },
    {
      id: '2',
      title: 'Audi A6 TDI S Line',
      variant: '40 TDI [204] Quattro 4dr S Tronic',
      numberPlate: 'AU21 A6T',
      condition: 'Used',
      timeListed: '1hr ago',
      price: '£23,995',
      dealer: {
        name: 'Metro Autohaus',
        address: '32 King’s Road, London, NW1 3BP',
        contactName: 'Elena Ford',
        phone: '0777 345 9012',
        email: 'sales@metroautohaus.co.uk',
      },
      vehicleInfo: {
        year: 2021,
        color: 'Black',
        engine: '2.0 L',
        miles: '21,000',
        fuel: 'Diesel',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: false,
      },
    },
    {
      id: '3',
      title: 'Mercedes-Benz C-Class',
      variant: 'C200 AMG Line 4dr 9G-Tronic',
      numberPlate: 'MB22 AMG',
      condition: 'Certified',
      timeListed: '3hrs ago',
      price: '£28,499',
      dealer: {
        name: 'Star Auto Traders',
        address: '221 Victoria Ave, Manchester, M16 8EX',
        contactName: 'Rahul Singh',
        phone: '0745 998 2311',
        email: 'sales@starautotraders.co.uk',
      },
      vehicleInfo: {
        year: 2022,
        color: 'Silver',
        engine: '1.5 L',
        miles: '15,000',
        fuel: 'Petrol',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: true,
      },
    },
  ];
  export const nearbyCarsData = [
    {
      id: '1',
      title: 'Alfa Romeo Giulia',
      variant: '2.0 Turbo Tributo Italiano 4dr Auto',
      numberPlate: 'EK74 PDF',
      condition: 'Used',
      timeListed: '2hrs ago',
      price: '£36,465',
      dealer: {
        name: 'Middlesex Motors',
        address: 'Ashby-De-La-Zouch, UK',
        contactName: 'Sales Team',
        phone: 'N/A',
        email: 'info@middlesexmotors.co.uk',
      },
      vehicleInfo: {
        year: 2022,
        color: 'Red',
        engine: '2.0 L',
        miles: '12,000',
        fuel: 'Petrol',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: true,
      },
    },
    {
      id: '2',
      title: 'Nissan Qashqai',
      variant: '1.3 DiG-T MH 158 N-Connecta 5dr',
      numberPlate: 'FV22 YHT',
      condition: 'Used',
      timeListed: '2hrs ago',
      price: '£16,655',
      dealer: {
        name: 'West End Cars',
        address: 'Ashby-De-La-Zouch, UK',
        contactName: 'Sales Team',
        phone: 'N/A',
        email: 'info@westendcars.co.uk',
      },
      vehicleInfo: {
        year: 2022,
        color: 'Grey',
        engine: '1.3 L',
        miles: '14,000',
        fuel: 'Petrol',
        transmission: 'Manual',
      },
      actions: {
        showAdditionalInfo: false,
        showDamageReport: false,
      },
    },
    {
      id: '3',
      title: 'Mercedes-Benz A-Class',
      variant: 'A2000 AMG Line 5dr Auto',
      numberPlate: 'KJ69 DSA',
      condition: 'Used',
      timeListed: '4hrs ago',
      price: '£15,788',
      dealer: {
        name: 'Harbour Trades',
        address: 'Ashby-De-La-Zouch, UK',
        contactName: 'Sales Team',
        phone: 'N/A',
        email: 'sales@harbourtrades.co.uk',
      },
      vehicleInfo: {
        year: 2021,
        color: 'Black',
        engine: '2.0 L',
        miles: '25,000',
        fuel: 'Petrol',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: false,
      },
    },
    {
      id: '4',
      title: 'Vauxhall Insignia Grand Sport',
      variant: '1.5T SRi VX-Line Nav 5dr',
      numberPlate: 'DY17 NGH',
      condition: 'Used',
      timeListed: '4hrs ago',
      price: '£10,399',
      dealer: {
        name: 'Alexander Matthews',
        address: 'Ashby-De-La-Zouch, UK',
        contactName: 'Sales Team',
        phone: 'N/A',
        email: 'info@alexandermatthews.co.uk',
      },
      vehicleInfo: {
        year: 2017,
        color: 'Silver',
        engine: '1.5 L',
        miles: '50,000',
        fuel: 'Diesel',
        transmission: 'Manual',
      },
      actions: {
        showAdditionalInfo: false,
        showDamageReport: true,
      },
    },
    {
      id: '5',
      title: 'Volkswagen Golf',
      variant: '160kW Premium 73 kWh 5dr Auto',
      numberPlate: 'KN22 PGJ',
      condition: 'Like New',
      timeListed: '5hrs ago',
      price: '£19,687',
      dealer: {
        name: 'West End Cars',
        address: 'Ashby-De-La-Zouch, UK',
        contactName: 'Sales Team',
        phone: 'N/A',
        email: 'info@westendcars.co.uk',
      },
      vehicleInfo: {
        year: 2022,
        color: 'White',
        engine: 'Electric',
        miles: '7,000',
        fuel: 'Electric',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: true,
      },
    },
    {
      id: '6',
      title: 'Hyundai IONIQ 5',
      variant: '225kW Ultimate 73 kWh 5dr AWD Auto',
      numberPlate: 'TR71 WER',
      condition: 'Certified',
      timeListed: '8hrs ago',
      price: '£20,138',
      dealer: {
        name: 'West End Cars',
        address: 'Ashby-De-La-Zouch, UK',
        contactName: 'Sales Team',
        phone: 'N/A',
        email: 'info@westendcars.co.uk',
      },
      vehicleInfo: {
        year: 2021,
        color: 'Black',
        engine: 'Electric',
        miles: '10,000',
        fuel: 'Electric',
        transmission: 'Automatic',
      },
      actions: {
        showAdditionalInfo: true,
        showDamageReport: false,
      },
    },
  ];

  export const defaultValues = {
    sort: 'Most Recent',
    distance: 'Any',
    model: 'Any',
    price: 'Any',
    year: 'Any',
    mileage: 'Any',
  };